# CAPSTONE PROJECT - PYTHON FUNDAMENTALS

In [39]:
#Importing necessary Libraries which will require to do the entire project
import numpy as np
import pandas as pd

## Task 1:
##### There are three different tables as given above. Please make three dataframe in python and save them as three .csv files. From Task 2 to Task 10, use the saved .csv files only.

### First I created a list of columns to combine it into three different DataFrames:
1. Employee DataFrame
2. Project DataFrame
3. Seniority Level DataFrame

In [40]:
#Creating Series of lists to use them as columns for the dataframes

id = pd.Series(['A001','A002','A003','A004','A005'])

project = pd.Series(['Project 1', 'Project 2', 'Project 3', 'Project 4', 'Project 5','Project 6', 'Project 7', 'Project 8', 'Project 9', 'Project 10', 
                     'Project 11', 'Project 12', 'Project 13', 'Project 14'])

name = pd.Series(["John Alter", "Alice Luxumberg", "Tom Sabestine", "Nina Adgra", "Amy Johny"])

gender = pd.Series(["M", "F", "M", "F", "F"])

city = pd.Series(["Paris", "London", "Berlin", "New York", "Madrid"])

age = pd.Series([25,27,29,31,30])

status = ["Finished", "Ongoing", "Failed"]

designation_level = [2,2,3,2,3]

status_list = pd.Series(["Finished", "Ongoing","Finished", "Ongoing", "Finished", "Failed", "Finished", "Failed", "Ongoing", "Finished", "Failed",
                         "Ongoing", "Finished", "Finished" ])

In [41]:
#Creating the Project DataFrame

proj_df = pd.DataFrame({
    "ID" : pd.Series(["A001", "A002", "A003", "A004", "A005", "A002", "A005", "A003", "A001", "A003", "A001", "A004", "A004", "A005"]),
    "Project" : project,
    "Cost" : pd.Series([1002000, 2000000, 4500000, 5500000, None, 680000, 400000, 350000, None, 300000, 2000000, 1000000, 3000000, 200000]),
    "Status" : pd.Series(["Finished", "Ongoing", "Finished", "Ongoing", "Finished", "Failed", "Finished", "Failed", "Ongoing", "Finished",
                          "Failed", "Ongoing", "Finished", "Finished"])
})

print("Project DataFrame: ")
proj_df

Project DataFrame:

      ID     Project       Cost    Status
0   A001   Project 1  1002000.0  Finished
1   A002   Project 2  2000000.0   Ongoing
2   A003   Project 3  4500000.0  Finished
3   A004   Project 4  5500000.0   Ongoing
4   A005   Project 5        NaN  Finished
5   A002   Project 6   680000.0    Failed
6   A005   Project 7   400000.0  Finished
7   A003   Project 8   350000.0    Failed
8   A001   Project 9        NaN   Ongoing
9   A003  Project 10   300000.0  Finished
10  A001  Project 11  2000000.0    Failed
11  A004  Project 12  1000000.0   Ongoing
12  A004  Project 13  3000000.0  Finished
13  A005  Project 14   200000.0  Finished

In [42]:
# Creating the Employee DataFrame

emp_df = pd.DataFrame ({
    "ID" : id,
    "Name" : name,
    "Gender" : gender,
    "City" : city,
    "Age" : age
})

print("Employee DataFrame: ")
emp_df

Employee DataFrame:

     ID             Name Gender      City  Age
0  A001       John Alter      M     Paris   25
1  A002  Alice Luxumberg      F    London   27
2  A003    Tom Sabestine      M    Berlin   29
3  A004       Nina Adgra      F  New York   31
4  A005        Amy Johny      F    Madrid   30

In [43]:
#Creating the Seniority Level DataFrame

senio_df = pd.DataFrame({
    "ID" : id,
    "Designation Level" : designation_level
})

print("Seniority Level DataFrame: ")
senio_df

Seniority Level DataFrame:

     ID  Designation Level
0  A001                  2
1  A002                  2
2  A003                  3
3  A004                  2
4  A005                  3

#### Saving the above three DataFrames to .csv files.

In [44]:
#Saving the DataFrames into .CSV files

emp_df.to_csv("employee_dataframe.csv" , index=False)
senio_df.to_csv("seniority_level_dataframe.csv", index=False)
proj_df.to_csv("project_dataframe.csv", index=False)

## Task 2:
##### The cost column in the dataframe “Project” has some missing values. Your task is to compute these missing values. Replace the missing values by running average. You should use the “For” loop for this task.

In [45]:
#Importing the project_dataframe.csv file as DataFrame
#Reading the project dataframe .csv file
project = pd.read_csv("project_dataframe.csv")

print("Project DataFrame: ")
project

Project DataFrame:

      ID     Project       Cost    Status
0   A001   Project 1  1002000.0  Finished
1   A002   Project 2  2000000.0   Ongoing
2   A003   Project 3  4500000.0  Finished
3   A004   Project 4  5500000.0   Ongoing
4   A005   Project 5        NaN  Finished
5   A002   Project 6   680000.0    Failed
6   A005   Project 7   400000.0  Finished
7   A003   Project 8   350000.0    Failed
8   A001   Project 9        NaN   Ongoing
9   A003  Project 10   300000.0  Finished
10  A001  Project 11  2000000.0    Failed
11  A004  Project 12  1000000.0   Ongoing
12  A004  Project 13  3000000.0  Finished
13  A005  Project 14   200000.0  Finished

In [46]:
#Creating a list of running averages using 'Cost' column in the project dataframe

running = 0
count = 0

# Calculating the average cost
average_cost = round(proj_df['Cost'].mean(), 2)

# Replacing missing values with average cost using a for loop
for i in range(len(proj_df)):
    if pd.isnull(proj_df.loc[i, 'Cost']):       #isnull() function is used to check if there is any null values
        proj_df.loc[i, 'Cost'] = average_cost

    #else function is used to iterate the loop if there is no missing values
    else:
        running += proj_df.loc[i, 'Cost']
        count += 1

print("Updated Project DataFrame:")
print(proj_df)

Updated Project DataFrame:
      ID     Project        Cost    Status
0   A001   Project 1  1002000.00  Finished
1   A002   Project 2  2000000.00   Ongoing
2   A003   Project 3  4500000.00  Finished
3   A004   Project 4  5500000.00   Ongoing
4   A005   Project 5  1744333.33  Finished
5   A002   Project 6   680000.00    Failed
6   A005   Project 7   400000.00  Finished
7   A003   Project 8   350000.00    Failed
8   A001   Project 9  1744333.33   Ongoing
9   A003  Project 10   300000.00  Finished
10  A001  Project 11  2000000.00    Failed
11  A004  Project 12  1000000.00   Ongoing
12  A004  Project 13  3000000.00  Finished
13  A005  Project 14   200000.00  Finished

In [47]:
#Saving the Task 2 DataFrames into .CSV files

proj_df.to_csv("updated_project_dataframe_average_cost.csv", index=False)

## Task 3:
##### Split the name column in the Employee dataframe into two new columns “First Name”, and “Last Name” and remove the older “name” column.

In [48]:
#Importing the employee_dataframe.csv file as DataFrame
#Reading the emmployee dataframe .csv file
employee = pd.read_csv("employee_dataframe.csv")

print("Employee DataFrame: ")
employee

Employee DataFrame:

     ID             Name Gender      City  Age
0  A001       John Alter      M     Paris   25
1  A002  Alice Luxumberg      F    London   27
2  A003    Tom Sabestine      M    Berlin   29
3  A004       Nina Adgra      F  New York   31
4  A005        Amy Johny      F    Madrid   30

In [49]:
#Usign .split() function to split the name
empl_df = emp_df["Name"].str.split()

print("Employee DataFrame: ")
empl_df

Employee DataFrame:

0         [John, Alter]
1    [Alice, Luxumberg]
2      [Tom, Sabestine]
3         [Nina, Adgra]
4          [Amy, Johny]
Name: Name, dtype: object

In [50]:
#splitting the `"Name"` column into two different columns...

emp_df[["First Name", "Last Name"]] = emp_df["Name"].str.split(' ', expand=True)

#dropping the "Name" column from theoriginal DataFrame using ,drop() method...
emp_df.drop("Name", axis = 1, inplace=True)

print("Employee DataFrame: ")
emp_df

Employee DataFrame:

     ID Gender      City  Age First Name  Last Name
0  A001      M     Paris   25       John      Alter
1  A002      F    London   27      Alice  Luxumberg
2  A003      M    Berlin   29        Tom  Sabestine
3  A004      F  New York   31       Nina      Adgra
4  A005      F    Madrid   30        Amy      Johny

In [51]:
#re-indexing `First Name` column...
cols = list(emp_df.columns)

#inserting the column in 1st index...
cols.insert(1, cols.pop(4))

#used to reorder the columns of a DataFrame.
emp_df = emp_df.reindex(columns=cols)

print("Employee DataFrame: ")
emp_df

Employee DataFrame:

     ID First Name Gender      City  Age  Last Name
0  A001       John      M     Paris   25      Alter
1  A002      Alice      F    London   27  Luxumberg
2  A003        Tom      M    Berlin   29  Sabestine
3  A004       Nina      F  New York   31      Adgra
4  A005        Amy      F    Madrid   30      Johny

In [52]:
#re-indexing 'Last Name' column...

cols = list(emp_df.columns)

#inserting the column in 2nd index...
cols.insert(2, cols.pop(5))

#used to reorder the columns of a DataFrame...
emp_df = emp_df.reindex(columns=cols)

print("Employee DataFrame: ")
emp_df

Employee DataFrame:

     ID First Name  Last Name Gender      City  Age
0  A001       John      Alter      M     Paris   25
1  A002      Alice  Luxumberg      F    London   27
2  A003        Tom  Sabestine      M    Berlin   29
3  A004       Nina      Adgra      F  New York   31
4  A005        Amy      Johny      F    Madrid   30

In [53]:
#Saving the Task 3 DataFrames into .CSV files

proj_df.to_csv("updated_employee_dataframe_with_firstLast_name.csv", index=False)

## Task 4:

##### Join all three dataframes in one single dataframe. Name it “Final”

In [54]:
#using pd.merge() function, to merge the dataframes.
#We can merge two dataframes at a time.

semi_final = pd.merge(emp_df, proj_df, on="ID")

print("Semi-Final DataFrame: ")
semi_final

Semi-Final DataFrame:

,ID,First Name,Last Name,Gender,City,Age,Project,Cost,Status
0,A001,John,Alter,M,Paris,25,Project 1,1002000.00,Finished
1,A001,John,Alter,M,Paris,25,Project 9,1744333.33,Ongoing
2,A001,John,Alter,M,Paris,25,Project 11,2000000.00,Failed
3,A002,Alice,Luxumberg,F,London,27,Project 2,2000000.00,Ongoing
4,A002,Alice,Luxumberg,F,London,27,Project 6,680000.00,Failed
5,A003,Tom,Sabestine,M,Berlin,29,Project 3,4500000.00,Finished
6,A003,Tom,Sabestine,M,Berlin,29,Project 8,350000.00,Failed
7,A003,Tom,Sabestine,M,Berlin,29,Project 10,300000.00,Finished
8,A004,Nina,Adgra,F,New York,31,Project 4,5500000.00,Ongoing
9,A004,Nina,Adgra,F,New York,31,Project 12,1000000.00,Ongoing
10,A004,Nina,Adgra,F,New York,31,Project 13,3000000.00,Finished
11,A005,Amy,Johny,F,Madrid,30,Project 5,1744333.33,Finished
12,A005,Amy,Johny,F,Madrid,30,Project 7,400000.00,Finished
13,A005,Amy,Johny,F,Madrid,30,Project 14,200000.00,Finished

In [55]:
#Merging of semi-final dataframe with seniority level dataframe, and naming it as Final DataFrame...
final = pd.merge(semi_final, senio_df, on="ID")

final.to_csv("Final_Dataframe.csv", index=False)

print("Final DataFrame: ")
final

Final DataFrame:

,ID,First Name,Last Name,Gender,City,Age,Project,Cost,Status,Designation Level
0,A001,John,Alter,M,Paris,25,Project 1,1002000.00,Finished,2
1,A001,John,Alter,M,Paris,25,Project 9,1744333.33,Ongoing,2
2,A001,John,Alter,M,Paris,25,Project 11,2000000.00,Failed,2
3,A002,Alice,Luxumberg,F,London,27,Project 2,2000000.00,Ongoing,2
4,A002,Alice,Luxumberg,F,London,27,Project 6,680000.00,Failed,2
5,A003,Tom,Sabestine,M,Berlin,29,Project 3,4500000.00,Finished,3
6,A003,Tom,Sabestine,M,Berlin,29,Project 8,350000.00,Failed,3
7,A003,Tom,Sabestine,M,Berlin,29,Project 10,300000.00,Finished,3
8,A004,Nina,Adgra,F,New York,31,Project 4,5500000.00,Ongoing,2
9,A004,Nina,Adgra,F,New York,31,Project 12,1000000.00,Ongoing,2
10,A004,Nina,Adgra,F,New York,31,Project 13,3000000.00,Finished,2
11,A005,Amy,Johny,F,Madrid,30,Project 5,1744333.33,Finished,3
12,A005,Amy,Johny,F,Madrid,30,Project 7,400000.00,Finished,3
13,A005,Amy,Johny,F,Madrid,30,Project 14,200000.00,Finished,3

In [56]:
#Saving the Task 4 DataFrames into .CSV files

proj_df.to_csv("Final_dataframe_after_Merging.csv", index=False)

## Task 5:

##### Add a new bonus column in the Final dataframe. Give a 5% bonus concerning project cost only to employees who have finished the projects.

In [57]:
# Creating a copy of final DataFrame
final_copy = final

print("Copy of Final DataFrame: ")
final_copy

Copy of Final DataFrame:

,ID,First Name,Last Name,Gender,City,Age,Project,Cost,Status,Designation Level
0,A001,John,Alter,M,Paris,25,Project 1,1002000.00,Finished,2
1,A001,John,Alter,M,Paris,25,Project 9,1744333.33,Ongoing,2
2,A001,John,Alter,M,Paris,25,Project 11,2000000.00,Failed,2
3,A002,Alice,Luxumberg,F,London,27,Project 2,2000000.00,Ongoing,2
4,A002,Alice,Luxumberg,F,London,27,Project 6,680000.00,Failed,2
5,A003,Tom,Sabestine,M,Berlin,29,Project 3,4500000.00,Finished,3
6,A003,Tom,Sabestine,M,Berlin,29,Project 8,350000.00,Failed,3
7,A003,Tom,Sabestine,M,Berlin,29,Project 10,300000.00,Finished,3
8,A004,Nina,Adgra,F,New York,31,Project 4,5500000.00,Ongoing,2
9,A004,Nina,Adgra,F,New York,31,Project 12,1000000.00,Ongoing,2
10,A004,Nina,Adgra,F,New York,31,Project 13,3000000.00,Finished,2
11,A005,Amy,Johny,F,Madrid,30,Project 5,1744333.33,Finished,3
12,A005,Amy,Johny,F,Madrid,30,Project 7,400000.00,Finished,3
13,A005,Amy,Johny,F,Madrid,30,Project 14,200000.00,Finished,3

In [58]:
#Using 'for' loop to creating a list of Bonus cost
#Later, inserted the list into the final dataframe
results_list=[]

for i, r in final_copy.iterrows():
    if(final_copy['Status'].iat[i] == 'Finished'):             #checking every index if "Finished" is present at any index of status column
        result = round((r['Cost']) + (r['Cost']) * 0.05, 2)    #if found, then bonus = cost + 5% of cost also rounding the bonus upto 2 decimal points
        results_list.append(result)                            #append() will add the result in the end of the list
    else:
        result = round((r['Cost']) + (r['Cost']) * 0, 2)       #if not, then no bonus
        results_list.append(result)

final_copy.insert(9, "Bonus-5%", results_list)                 #inserting the bonus-5% column into the final Dataframe at index 9

print("Updated Final DataFrame: ")
final_copy

Updated Final DataFrame:

,ID,First Name,Last Name,Gender,City,Age,Project,Cost,Status,Bonus-5%,Designation Level
0,A001,John,Alter,M,Paris,25,Project 1,1002000.00,Finished,1052100.00,2
1,A001,John,Alter,M,Paris,25,Project 9,1744333.33,Ongoing,1744333.33,2
2,A001,John,Alter,M,Paris,25,Project 11,2000000.00,Failed,2000000.00,2
3,A002,Alice,Luxumberg,F,London,27,Project 2,2000000.00,Ongoing,2000000.00,2
4,A002,Alice,Luxumberg,F,London,27,Project 6,680000.00,Failed,680000.00,2
5,A003,Tom,Sabestine,M,Berlin,29,Project 3,4500000.00,Finished,4725000.00,3
6,A003,Tom,Sabestine,M,Berlin,29,Project 8,350000.00,Failed,350000.00,3
7,A003,Tom,Sabestine,M,Berlin,29,Project 10,300000.00,Finished,315000.00,3
8,A004,Nina,Adgra,F,New York,31,Project 4,5500000.00,Ongoing,5500000.00,2
9,A004,Nina,Adgra,F,New York,31,Project 12,1000000.00,Ongoing,1000000.00,2
10,A004,Nina,Adgra,F,New York,31,Project 13,3000000.00,Finished,3150000.00,2
11,A005,Amy,Johny,F,Madrid,30,Project 5,1744333.33,Finished,1831550.00,3
12,A005,Amy,Johny,F,Madrid,30,Project 7,400000.00,Finished,420000.00,3
13,A005,Amy,Johny,F,Madrid,30,Project 14,200000.00,Finished,210000.00,3

In [59]:
#Saving the Task 5 DataFrames into .CSV files

proj_df.to_csv("Updated_Final_dataframe_with_bonus.csv", index=False)

## Task 6:

##### Demote the designation level by 1, whose projects have status “fail”. Delete the employees record whose designation level is above 4.

In [60]:
#As per the task given, I used 'for' loop to create a list of new designations
#Later,inserted the list into the final dataframe

new_designation = []

for i, r in final_copy.iterrows():
    #checking if the status of the project is 'Failed'...
    if (final_copy["Status"].iat[i] == 'Failed'):
        result = (r['Designation Level']) - 1    #if 'Failed' then demote 1 level from designation level
        new_designation.append(result)
    else:
        result = (r['Designation Level']) - 0    #if not 'Failed' then do not demote any level from designation level
        new_designation.append(result)

#inesrting the new designation column...
final_copy.insert(10, 'Designation', new_designation)     #inserting the Designation column into the final Dataframe at index 10

print("Updated Final DataFrame: ")
final_copy

Updated Final DataFrame:

,ID,First Name,Last Name,Gender,City,Age,Project,Cost,Status,Bonus-5%,Designation,Designation Level
0,A001,John,Alter,M,Paris,25,Project 1,1002000.00,Finished,1052100.00,2,2
1,A001,John,Alter,M,Paris,25,Project 9,1744333.33,Ongoing,1744333.33,2,2
2,A001,John,Alter,M,Paris,25,Project 11,2000000.00,Failed,2000000.00,1,2
3,A002,Alice,Luxumberg,F,London,27,Project 2,2000000.00,Ongoing,2000000.00,2,2
4,A002,Alice,Luxumberg,F,London,27,Project 6,680000.00,Failed,680000.00,1,2
5,A003,Tom,Sabestine,M,Berlin,29,Project 3,4500000.00,Finished,4725000.00,3,3
6,A003,Tom,Sabestine,M,Berlin,29,Project 8,350000.00,Failed,350000.00,2,3
7,A003,Tom,Sabestine,M,Berlin,29,Project 10,300000.00,Finished,315000.00,3,3
8,A004,Nina,Adgra,F,New York,31,Project 4,5500000.00,Ongoing,5500000.00,2,2
9,A004,Nina,Adgra,F,New York,31,Project 12,1000000.00,Ongoing,1000000.00,2,2
10,A004,Nina,Adgra,F,New York,31,Project 13,3000000.00,Finished,3150000.00,2,2
11,A005,Amy,Johny,F,Madrid,30,Project 5,1744333.33,Finished,1831550.00,3,3
12,A005,Amy,Johny,F,Madrid,30,Project 7,400000.00,Finished,420000.00,3,3
13,A005,Amy,Johny,F,Madrid,30,Project 14,200000.00,Finished,210000.00,3,3

In [61]:
#droping the previous designation level
final_copy.drop("Designation Level", axis=1 , inplace=True)

In [62]:
#DataFrame with updated and renamed Designation Levels

final_copy.rename(columns={'Designation': 'Designation Level'}, inplace=True)

print("Updated Final DataFrame: ")
final_copy

Updated Final DataFrame:

,ID,First Name,Last Name,Gender,City,Age,Project,Cost,Status,Bonus-5%,Designation Level
0,A001,John,Alter,M,Paris,25,Project 1,1002000.00,Finished,1052100.00,2
1,A001,John,Alter,M,Paris,25,Project 9,1744333.33,Ongoing,1744333.33,2
2,A001,John,Alter,M,Paris,25,Project 11,2000000.00,Failed,2000000.00,1
3,A002,Alice,Luxumberg,F,London,27,Project 2,2000000.00,Ongoing,2000000.00,2
4,A002,Alice,Luxumberg,F,London,27,Project 6,680000.00,Failed,680000.00,1
5,A003,Tom,Sabestine,M,Berlin,29,Project 3,4500000.00,Finished,4725000.00,3
6,A003,Tom,Sabestine,M,Berlin,29,Project 8,350000.00,Failed,350000.00,2
7,A003,Tom,Sabestine,M,Berlin,29,Project 10,300000.00,Finished,315000.00,3
8,A004,Nina,Adgra,F,New York,31,Project 4,5500000.00,Ongoing,5500000.00,2
9,A004,Nina,Adgra,F,New York,31,Project 12,1000000.00,Ongoing,1000000.00,2
10,A004,Nina,Adgra,F,New York,31,Project 13,3000000.00,Finished,3150000.00,2
11,A005,Amy,Johny,F,Madrid,30,Project 5,1744333.33,Finished,1831550.00,3
12,A005,Amy,Johny,F,Madrid,30,Project 7,400000.00,Finished,420000.00,3
13,A005,Amy,Johny,F,Madrid,30,Project 14,200000.00,Finished,210000.00,3

In [63]:
#deleting the employee records having designation level > 4

to_delete = 0

for index, row in final_copy.iterrows():
    if row["Designation Level"] > 4:                      #checking if any of the employees have designation level > 4
        to_delete.append(index)                           #if found, then adding the index at the end of the list `to_delete`
        final_copy.drop(to_delete, inplace=True)          #then, removing the index from the Dataframe

print("Updated Final DataFrame: ")
final_copy

Updated Final DataFrame:

,ID,First Name,Last Name,Gender,City,Age,Project,Cost,Status,Bonus-5%,Designation Level
0,A001,John,Alter,M,Paris,25,Project 1,1002000.00,Finished,1052100.00,2
1,A001,John,Alter,M,Paris,25,Project 9,1744333.33,Ongoing,1744333.33,2
2,A001,John,Alter,M,Paris,25,Project 11,2000000.00,Failed,2000000.00,1
3,A002,Alice,Luxumberg,F,London,27,Project 2,2000000.00,Ongoing,2000000.00,2
4,A002,Alice,Luxumberg,F,London,27,Project 6,680000.00,Failed,680000.00,1
5,A003,Tom,Sabestine,M,Berlin,29,Project 3,4500000.00,Finished,4725000.00,3
6,A003,Tom,Sabestine,M,Berlin,29,Project 8,350000.00,Failed,350000.00,2
7,A003,Tom,Sabestine,M,Berlin,29,Project 10,300000.00,Finished,315000.00,3
8,A004,Nina,Adgra,F,New York,31,Project 4,5500000.00,Ongoing,5500000.00,2
9,A004,Nina,Adgra,F,New York,31,Project 12,1000000.00,Ongoing,1000000.00,2
10,A004,Nina,Adgra,F,New York,31,Project 13,3000000.00,Finished,3150000.00,2
11,A005,Amy,Johny,F,Madrid,30,Project 5,1744333.33,Finished,1831550.00,3
12,A005,Amy,Johny,F,Madrid,30,Project 7,400000.00,Finished,420000.00,3
13,A005,Amy,Johny,F,Madrid,30,Project 14,200000.00,Finished,210000.00,3

In [64]:
#Saving the Task 6 DataFrames into .CSV files

proj_df.to_csv("Updated_Final_dataframe_with_designation.csv", index=False)

## Task 7:

##### Add “Mr.” and “Mrs.” to the first name column and drop the gender column.

In [65]:
#Adding "Mr." to the first name of males and "Mrs." to the first name of females

final_copy['First Name'] = np.where(final_copy['Gender'] == 'M', 'Mr. ' + final_copy['First Name'], 'Mrs. ' + final_copy['First Name'])

#dropping the Gender column from the dataframe
final_copy = final_copy.drop("Gender", axis=1)

print("Updated Final DataFrame: ")
final_copy

Updated Final DataFrame:

,ID,First Name,Last Name,City,Age,Project,Cost,Status,Bonus-5%,Designation Level
0,A001,Mr. John,Alter,Paris,25,Project 1,1002000.00,Finished,1052100.00,2
1,A001,Mr. John,Alter,Paris,25,Project 9,1744333.33,Ongoing,1744333.33,2
2,A001,Mr. John,Alter,Paris,25,Project 11,2000000.00,Failed,2000000.00,1
3,A002,Mrs. Alice,Luxumberg,London,27,Project 2,2000000.00,Ongoing,2000000.00,2
4,A002,Mrs. Alice,Luxumberg,London,27,Project 6,680000.00,Failed,680000.00,1
5,A003,Mr. Tom,Sabestine,Berlin,29,Project 3,4500000.00,Finished,4725000.00,3
6,A003,Mr. Tom,Sabestine,Berlin,29,Project 8,350000.00,Failed,350000.00,2
7,A003,Mr. Tom,Sabestine,Berlin,29,Project 10,300000.00,Finished,315000.00,3
8,A004,Mrs. Nina,Adgra,New York,31,Project 4,5500000.00,Ongoing,5500000.00,2
9,A004,Mrs. Nina,Adgra,New York,31,Project 12,1000000.00,Ongoing,1000000.00,2
10,A004,Mrs. Nina,Adgra,New York,31,Project 13,3000000.00,Finished,3150000.00,2
11,A005,Mrs. Amy,Johny,Madrid,30,Project 5,1744333.33,Finished,1831550.00,3
12,A005,Mrs. Amy,Johny,Madrid,30,Project 7,400000.00,Finished,420000.00,3
13,A005,Mrs. Amy,Johny,Madrid,30,Project 14,200000.00,Finished,210000.00,3

In [66]:
#Saving the Task 7 DataFrames into .CSV files

proj_df.to_csv("Updated_Final_dataframe_with_prefix.csv", index=False)

## Task 8:

##### Promote designation level by 1 for the employees whose age is more than 29 years using IF condition.

In [67]:
#used iteration of rows and if function to promote designation level by 1 for the wmployees having age > 29

for i, r in final_copy.iterrows():
    if r["Age"] > 29:
        final_copy.loc[i, 'Designation Level'] += 1       # If any employee has age > 29, promote designation level by 1

    else:
        final_copy.loc[i, 'Designation Level'] += 0       # If any employee has age <= 29, designation level remains the same

print("Updated Final DataFrame: ")
final_copy

Updated Final DataFrame:

,ID,First Name,Last Name,City,Age,Project,Cost,Status,Bonus-5%,Designation Level
0,A001,Mr. John,Alter,Paris,25,Project 1,1002000.00,Finished,1052100.00,2
1,A001,Mr. John,Alter,Paris,25,Project 9,1744333.33,Ongoing,1744333.33,2
2,A001,Mr. John,Alter,Paris,25,Project 11,2000000.00,Failed,2000000.00,1
3,A002,Mrs. Alice,Luxumberg,London,27,Project 2,2000000.00,Ongoing,2000000.00,2
4,A002,Mrs. Alice,Luxumberg,London,27,Project 6,680000.00,Failed,680000.00,1
5,A003,Mr. Tom,Sabestine,Berlin,29,Project 3,4500000.00,Finished,4725000.00,3
6,A003,Mr. Tom,Sabestine,Berlin,29,Project 8,350000.00,Failed,350000.00,2
7,A003,Mr. Tom,Sabestine,Berlin,29,Project 10,300000.00,Finished,315000.00,3
8,A004,Mrs. Nina,Adgra,New York,31,Project 4,5500000.00,Ongoing,5500000.00,3
9,A004,Mrs. Nina,Adgra,New York,31,Project 12,1000000.00,Ongoing,1000000.00,3
10,A004,Mrs. Nina,Adgra,New York,31,Project 13,3000000.00,Finished,3150000.00,3
11,A005,Mrs. Amy,Johny,Madrid,30,Project 5,1744333.33,Finished,1831550.00,4
12,A005,Mrs. Amy,Johny,Madrid,30,Project 7,400000.00,Finished,420000.00,4
13,A005,Mrs. Amy,Johny,Madrid,30,Project 14,200000.00,Finished,210000.00,4

In [68]:
#Saving the Task 8 DataFrames into .CSV files

proj_df.to_csv("Updated_Final_dataframe_with_designation_age.csv", index=False)

## Task 9:

##### Add the cost of all projects for each Employee and save it in new dataframe “TotalProjCost” with three columns ID, First Name, and Total cost

In [69]:
#Grouping by employee ID and first name, and calculating the total project cost by summing up the cost column
TotalProjCost = final_copy.groupby(['ID', 'First Name'])['Cost'].sum().reset_index()

#Renaming the columns
TotalProjCost.columns = ['ID', 'First Name', 'Total Cost']

#converting the TotalProjCost Dataframe  to a .csv file
TotalProjCost.to_csv("Total_Project_Cost_Dataframe.csv")

print("TotalProjCost DataFrame: ")
TotalProjCost

TotalProjCost DataFrame:

     ID  First Name  Total Cost
0  A001    Mr. John  4746333.33
1  A002  Mrs. Alice  2680000.00
2  A003     Mr. Tom  5150000.00
3  A004   Mrs. Nina  9500000.00
4  A005    Mrs. Amy  2344333.33

In [70]:
#Saving the Task 9 DataFrames into .CSV files

TotalProjCost.to_csv("TotalProjCost_dataframe.csv", index=False)

## Task 10:

##### Print all the employee details whose city name contains the letter “o” in it.

In [71]:
#Printing employee details whose city name contains the letter 'o'

#define a function for searching of letter 'o' in the city column
def city(col, value):
    return final_copy[final_copy['City'].str.contains('o', case=False)]

#Generating the city names containing 'o' and print it...
dataframe = city('City', 'o')

In [74]:
# Final DataFrame
print("Updated DataFrame:")
print(final_copy)

Updated DataFrame:
      ID  First Name  Last Name      City  Age     Project        Cost  \
0   A001    Mr. John      Alter     Paris   25   Project 1  1002000.00
1   A001    Mr. John      Alter     Paris   25   Project 9  1744333.33
2   A001    Mr. John      Alter     Paris   25  Project 11  2000000.00
3   A002  Mrs. Alice  Luxumberg    London   27   Project 2  2000000.00
4   A002  Mrs. Alice  Luxumberg    London   27   Project 6   680000.00
5   A003     Mr. Tom  Sabestine    Berlin   29   Project 3  4500000.00
6   A003     Mr. Tom  Sabestine    Berlin   29   Project 8   350000.00
7   A003     Mr. Tom  Sabestine    Berlin   29  Project 10   300000.00
8   A004   Mrs. Nina      Adgra  New York   31   Project 4  5500000.00
9   A004   Mrs. Nina      Adgra  New York   31  Project 12  1000000.00
10  A004   Mrs. Nina      Adgra  New York   31  Project 13  3000000.00
11  A005    Mrs. Amy      Johny    Madrid   30   Project 5  1744333.33
12  A005    Mrs. Amy      Johny    Madrid   30   Project 7   400000.00
13  A005    Mrs. Amy      Johny    Madrid   30  Project 14   200000.00

      Status    Bonus-5%  Designation Level
0   Finished  1052100.00                  2
1    Ongoing  1744333.33                  2
2     Failed  2000000.00                  1
3    Ongoing  2000000.00                  2
4     Failed   680000.00                  1
5   Finished  4725000.00                  3
6     Failed   350000.00                  2
7   Finished   315000.00                  3
8    Ongoing  5500000.00                  3
9    Ongoing  1000000.00                  3
10  Finished  3150000.00                  3
11  Finished  1831550.00                  4
12  Finished   420000.00                  4
13  Finished   210000.00                  4

In [75]:
#Saving the Task 10 DataFrames into .CSV files

final_copy.to_csv("Updated_dataframe.csv", index=False)